import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./../styles/globals.css";
import "./../styles/colors.css";

const openSansFont = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "YouLyst | Market Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSansFont.variable}`}>
        {children}
        <div id="portal"></div>
      </body>
    </html>
  );
}
